apiVersion: v1
kind: Pod
metadata:
  labels:
    my-kubernetes-label: true
spec:
  containers:
    - name: cml-dvc
      image: dvcorg/cml:0-dvc2-base1-gpu
      command: ['sh', '-c', 'sleep infinity']
      tty: true
      volumeMounts:
        - name: ikurtz-aws-sso-config
          mountPath: /root/.aws/config
          readOnly: true
      securityContext:
        privileged: true  # Add the privileged option
    - name: cml-dvc-pythonvenv
      image: python:3
      command: ['sh', '-c', 'sleep infinity']
      tty: true
      volumeMounts:
        - name: source
          mountPath: /workspace/source
        - name: venv
          mountPath: /workspace/venv
        - name: ikurtz-aws-sso-config
          mountPath: /root/.aws/config
          readOnly: true
      securityContext:
        privileged: true  # Add the privileged option
  volumes:
    - name: source
      emptyDir: {}
    - name: venv
      emptyDir: {}
    - name: ikurtz-aws-sso-config
      configMap:
        name: ikurtz-aws-sso-config-map
