apiVersion: v1
kind: Pod
metadata:
  labels:
    my-kubernetes-label: true
spec:
  containers:
    - name: cml-dvc
      image: ghcr.io/iterative/cml:0-dvc2-base1
      command: ['sh', '-c', 'sleep infinity']
      tty: true
      volumeMounts:
        - name: ikurtz-aws-sso-config
          mountPath: /root/.aws/config
          readOnly: true
      securityContext:
        privileged: true  # Add the privileged option
    - name: cml-dvc-pythonvenv
      image: 268150017804.dkr.ecr.us-east-1.amazonaws.com/cbci-aws-workshop-registry/cml:cml-dvc-pythonvenv
      command: ['sh', '-c', 'sleep infinity']
      tty: true
      volumeMounts:
        - name: ikurtz-aws-sso-config
          mountPath: /root/.aws/config
          readOnly: true
      securityContext:
        privileged: true  # Add the privileged option
  volumes:
    - name: ikurtz-aws-sso-config
      configMap:
        name: ikurtz-aws-sso-config-map
